<div class="row">
    <div class="col s12">
        <div class="row">
            <div class="input-field col s12">
                <form method="post" class="col s12">
                <i class="material-icons prefix">edit</i>
                <input type="text" id="escola" name="escola" class="">
                <label for="escola">Digite o código ou o nome da Unidade</label>
                </form>
            </div>
        </div>
    </div>
</div>


<?php
if($_SERVER['REQUEST_METHOD']=='POST'):
    //posso usar apenas este se na página tiver apenas um form? ou preciso usar o
    if($_POST['escola'] == null):
        echo '<div class="col s12 center red-text">Ops, você precisa informar os dados para a pesquisa!</div>';
        else:
            $post = explode(' - ',$_POST['escola']);
            $envio = new Search();
             //$post[0] é o código da escola que será usado para pesquisar no banco
        if($envio->searchSchool($post[0])== true):
            else:

        endif;
    endif;
endif;




